#!/usr/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT

from pathlib import Path


TEMPLATE_ROOT = Path(__file__).resolve().parents[2] / 'src' / 'apebind' / 'templates'


def test_generated_templates_start_with_a_machine_owned_marker():
    expected_markers = {
        'java': '// Generated by APEBind. Do not edit directly.',
        'node': '// Generated by APEBind. Do not edit directly.',
        'python': '# Generated by APEBind. Do not edit directly.',
    }
    markdown_marker = '<!-- Generated by APEBind. Do not edit directly. -->'

    for template_path in TEMPLATE_ROOT.rglob('*.j2'):
        relative_path = template_path.relative_to(TEMPLATE_ROOT)
        if template_path.name == 'package.json.j2':
            continue

        first_line = template_path.read_text(encoding='utf-8').splitlines()[0]
        if template_path.name == 'generated_readme.md.j2':
            assert first_line == markdown_marker, relative_path
            continue

        if template_path.name == 'pom.xml.j2':
            assert first_line == markdown_marker, relative_path
            continue

        assert first_line == expected_markers[relative_path.parts[0]], relative_path


def test_generated_node_package_declares_apebind_ownership():
    package_template = TEMPLATE_ROOT / 'node' / 'package.json.j2'

    assert '"apebindGenerated": true' in package_template.read_text(encoding='utf-8')
